
package stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceManageFranchise", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceManageFranchise {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "coucou", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub.Coucou")
    @ResponseWrapper(localName = "coucouResponse", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub.CoucouResponse")
    public void coucou();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "creerBoutique", targetNamespace = "")
    @RequestWrapper(localName = "creerBoutique2", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub.CreerBoutique2")
    @ResponseWrapper(localName = "creerBoutique2Response", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub.CreerBoutique2Response")
    public boolean creerBoutique2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Cookie arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<Commande> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Double arg3);

}
