
package stub1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceManageFranchise", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceManageFranchise {


    /**
     * 
     * @param cookie
     * @param tax
     * @param name
     * @param listcookies
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "creerBoutique", targetNamespace = "")
    @RequestWrapper(localName = "creerBoutique2", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.CreerBoutique2")
    @ResponseWrapper(localName = "creerBoutique2Response", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.CreerBoutique2Response")
    public String creerBoutique2(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "cookie", targetNamespace = "")
        Cookie cookie,
        @WebParam(name = "listcookies", targetNamespace = "")
        List<Commande> listcookies,
        @WebParam(name = "tax", targetNamespace = "")
        Double tax);

}
