
package stub1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceManageFranchise", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceManageFranchise {


    /**
     * 
     * @return
     *     returns java.util.List<stub1.Magasin>
     */
    @WebMethod
    @WebResult(name = "regarderListeMagasin", targetNamespace = "")
    @RequestWrapper(localName = "getListeMagasin", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.GetListeMagasin")
    @ResponseWrapper(localName = "getListeMagasinResponse", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.GetListeMagasinResponse")
    public List<Magasin> getListeMagasin();

    /**
     * 
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "creerBoutique", targetNamespace = "")
    @RequestWrapper(localName = "creerBoutique2", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.CreerBoutique2")
    @ResponseWrapper(localName = "creerBoutique2Response", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.CreerBoutique2Response")
    public boolean creerBoutique2(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "creerUnCookie", targetNamespace = "")
    @RequestWrapper(localName = "creerUnCookie", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.CreerUnCookie")
    @ResponseWrapper(localName = "creerUnCookieResponse", targetNamespace = "http://www.polytech.unice.fr/serviceManageFranchise", className = "stub1.CreerUnCookieResponse")
    public String creerUnCookie(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2);

}
