
package stub1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceImplementsService", targetNamespace = "http://www.polytech.unice.fr/si/4a/appserv/demos", wsdlLocation = "http://localhost:8080//webservices/Fefe?wsdl")
public class ServiceImplementsService
    extends javax.xml.ws.Service
{

    private final static URL SERVICEIMPLEMENTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEIMPLEMENTSSERVICE_EXCEPTION;
    private final static QName SERVICEIMPLEMENTSSERVICE_QNAME = new QName("http://www.polytech.unice.fr/si/4a/appserv/demos", "ServiceImplementsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080//webservices/Fefe?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEIMPLEMENTSSERVICE_WSDL_LOCATION = url;
        SERVICEIMPLEMENTSSERVICE_EXCEPTION = e;
    }

    public ServiceImplementsService() {
        super(__getWsdlLocation(), SERVICEIMPLEMENTSSERVICE_QNAME);
    }

    public ServiceImplementsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEIMPLEMENTSSERVICE_QNAME, features);
    }

    public ServiceImplementsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEIMPLEMENTSSERVICE_QNAME);
    }

    public ServiceImplementsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEIMPLEMENTSSERVICE_QNAME, features);
    }

    public ServiceImplementsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceImplementsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServiceImplementsPort")
    public stub1.Service getServiceImplementsPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/appserv/demos", "ServiceImplementsPort"), Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServiceImplementsPort")
    public stub1.Service getServiceImplementsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/si/4a/appserv/demos", "ServiceImplementsPort"), Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEIMPLEMENTSSERVICE_EXCEPTION!= null) {
            throw SERVICEIMPLEMENTSSERVICE_EXCEPTION;
        }
        return SERVICEIMPLEMENTSSERVICE_WSDL_LOCATION;
    }

}
