
package stub1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://webservice.demo.se.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param cookie
     * @param tax
     * @param name
     * @param listeCommande
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "created", targetNamespace = "")
    @RequestWrapper(localName = "creerBoutique", targetNamespace = "http://webservice.demo.se.polytech.unice.fr/", className = "stub1.CreerBoutique")
    @ResponseWrapper(localName = "creerBoutiqueResponse", targetNamespace = "http://webservice.demo.se.polytech.unice.fr/", className = "stub1.CreerBoutiqueResponse")
    public boolean creerBoutique(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "cookie", targetNamespace = "")
        Cookie cookie,
        @WebParam(name = "listeCommande", targetNamespace = "")
        List<Commande> listeCommande,
        @WebParam(name = "tax", targetNamespace = "")
        Double tax);

}
