
package stub2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicePrendreRendezvousBeanService", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous", wsdlLocation = "http://localhost:8080//webservices/ServicePrendreRendezvous?wsdl")
public class ServicePrendreRendezvousBeanService
    extends Service
{

    private final static URL SERVICEPRENDRERENDEZVOUSBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEPRENDRERENDEZVOUSBEANSERVICE_EXCEPTION;
    private final static QName SERVICEPRENDRERENDEZVOUSBEANSERVICE_QNAME = new QName("http://www.polytech.unice.fr/servicePrendreRendezvous", "ServicePrendreRendezvousBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080//webservices/ServicePrendreRendezvous?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEPRENDRERENDEZVOUSBEANSERVICE_WSDL_LOCATION = url;
        SERVICEPRENDRERENDEZVOUSBEANSERVICE_EXCEPTION = e;
    }

    public ServicePrendreRendezvousBeanService() {
        super(__getWsdlLocation(), SERVICEPRENDRERENDEZVOUSBEANSERVICE_QNAME);
    }

    public ServicePrendreRendezvousBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEPRENDRERENDEZVOUSBEANSERVICE_QNAME, features);
    }

    public ServicePrendreRendezvousBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEPRENDRERENDEZVOUSBEANSERVICE_QNAME);
    }

    public ServicePrendreRendezvousBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEPRENDRERENDEZVOUSBEANSERVICE_QNAME, features);
    }

    public ServicePrendreRendezvousBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicePrendreRendezvousBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicePrendreRendezvous
     */
    @WebEndpoint(name = "ServicePrendreRendezvousBeanPort")
    public ServicePrendreRendezvous getServicePrendreRendezvousBeanPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/servicePrendreRendezvous", "ServicePrendreRendezvousBeanPort"), ServicePrendreRendezvous.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePrendreRendezvous
     */
    @WebEndpoint(name = "ServicePrendreRendezvousBeanPort")
    public ServicePrendreRendezvous getServicePrendreRendezvousBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/servicePrendreRendezvous", "ServicePrendreRendezvousBeanPort"), ServicePrendreRendezvous.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEPRENDRERENDEZVOUSBEANSERVICE_EXCEPTION!= null) {
            throw SERVICEPRENDRERENDEZVOUSBEANSERVICE_EXCEPTION;
        }
        return SERVICEPRENDRERENDEZVOUSBEANSERVICE_WSDL_LOCATION;
    }

}
