
package stub2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicePrendreRendezvous", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePrendreRendezvous {


    /**
     * 
     * @return
     *     returns java.util.List<stub2.Rendezvous>
     */
    @WebMethod
    @WebResult(name = "regarderListeRendezvous", targetNamespace = "")
    @RequestWrapper(localName = "getListeRendezvous", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous", className = "stub2.GetListeRendezvous")
    @ResponseWrapper(localName = "getListeRendezvousResponse", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous", className = "stub2.GetListeRendezvousResponse")
    public List<Rendezvous> getListeRendezvous();

    /**
     * 
     * @return
     *     returns java.util.List<stub2.Magasin>
     */
    @WebMethod
    @WebResult(name = "regarderListeMagasin", targetNamespace = "")
    @RequestWrapper(localName = "getListeMagasin", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous", className = "stub2.GetListeMagasin")
    @ResponseWrapper(localName = "getListeMagasinResponse", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous", className = "stub2.GetListeMagasinResponse")
    public List<Magasin> getListeMagasin();

    /**
     * 
     * @param magasin
     * @param date
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "creerBoutique", targetNamespace = "")
    @RequestWrapper(localName = "prendreRendezvous", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous", className = "stub2.PrendreRendezvous")
    @ResponseWrapper(localName = "prendreRendezvousResponse", targetNamespace = "http://www.polytech.unice.fr/servicePrendreRendezvous", className = "stub2.PrendreRendezvousResponse")
    public boolean prendreRendezvous(
        @WebParam(name = "magasin", targetNamespace = "")
        String magasin,
        @WebParam(name = "date", targetNamespace = "")
        String date);

}
