
package stub3;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicePasseUneCommande", targetNamespace = "http://www.polytech.unice.fr/ServicePasseUneCommande")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePasseUneCommande {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "choisirCookies", targetNamespace = "")
    @RequestWrapper(localName = "choisirCookies", targetNamespace = "http://www.polytech.unice.fr/ServicePasseUneCommande", className = "stub3.ChoisirCookies")
    @ResponseWrapper(localName = "choisirCookiesResponse", targetNamespace = "http://www.polytech.unice.fr/ServicePasseUneCommande", className = "stub3.ChoisirCookiesResponse")
    public List<String> choisirCookies();

    /**
     * 
     * @param prixHT
     * @param rendevous
     * @param cookies
     * @return
     *     returns stub3.Commande
     */
    @WebMethod
    @WebResult(name = "passerUneCommande", targetNamespace = "")
    @RequestWrapper(localName = "passerUneCommande", targetNamespace = "http://www.polytech.unice.fr/ServicePasseUneCommande", className = "stub3.PasserUneCommande")
    @ResponseWrapper(localName = "passerUneCommandeResponse", targetNamespace = "http://www.polytech.unice.fr/ServicePasseUneCommande", className = "stub3.PasserUneCommandeResponse")
    public Commande passerUneCommande(
        @WebParam(name = "prixHT", targetNamespace = "")
        Double prixHT,
        @WebParam(name = "rendevous", targetNamespace = "")
        String rendevous,
        @WebParam(name = "cookies", targetNamespace = "")
        String cookies);

    /**
     * 
     * @return
     *     returns java.util.List<stub3.Commande>
     */
    @WebMethod
    @WebResult(name = "regarderListeCommande", targetNamespace = "")
    @RequestWrapper(localName = "getListeCommande", targetNamespace = "http://www.polytech.unice.fr/ServicePasseUneCommande", className = "stub3.GetListeCommande")
    @ResponseWrapper(localName = "getListeCommandeResponse", targetNamespace = "http://www.polytech.unice.fr/ServicePasseUneCommande", className = "stub3.GetListeCommandeResponse")
    public List<Commande> getListeCommande();

}
